---
title: "Code Book"
author: "David English"
date: "11/30/2016"
output: html_document
---

## Original Data

The data used in this project was taken from the **Human Activity Recognition Using Smartphones Data Set** on the *UCI machine learning repository*. The features investigated are described in detail in the *"features_info.txt"* file.

The relevant files can be found at the link below.

[Data files](https://d396qusza40orc.cloudfront.net/getdata%2Fprojectfiles%2FUCI%20HAR%20Dataset.zip)

A description of these data can be found at this link.

[Data description](http://archive.ics.uci.edu/ml/datasets/Human+Activity+Recognition+Using+Smartphones)

## Data Used

The observations were made upon 30 different subjects (people) and for 6 different activities. These values were used as the keys in the data extracted for this project.

The data of interest relates to those features that are either a mean or a standard deviation measurement. All relevant data points were extracted and the mean of these values, with respect to the two keys, was placed in the tidy data set.

## Tidy Data Set

For completeness I have listed below all variables recorded in the tidy data set.

* Subject
Each subject was given a unique identifier numbered from 1 to 30. This column specifiers which subject the observation corresponds to.

* Activity
The activities were assigned one of 6 possible values. These are;
      + WALKING
      + WALKING_UPSTAIRS
      + WALKING_DOWNSTAIRS
      + SITTING
      + STANDING
      + LAYING

* tBodyAcc_mean_X

* tBodyAcc_mean_Y

* tBodyAcc_mean_Z

* tBodyAcc_std_X

* tBodyAcc_std_Y

* tBodyAcc_std_Z

* tGravityAcc_mean_X

* tGravityAcc_mean_Y

* tGravityAcc_mean_Z

* tGravityAcc_std_X

* tGravityAcc_std_Y

* tGravityAcc_std_Z

* tBodyAccJerk_mean_X

* tBodyAccJerk_mean_Y

* tBodyAccJerk_mean_Z

* tBodyAccJerk_std_X

* tBodyAccJerk_std_Y

* tBodyAccJerk_std_Z

* tBodyGyro_mean_X

* tBodyGyro_mean_Y

* tBodyGyro_mean_Z

* tBodyGyro_std_X

* tBodyGyro_std_Y

* tBodyGyro_std_Z

* tBodyGyroJerk_mean_X

* tBodyGyroJerk_mean_Y

* tBodyGyroJerk_mean_Z

* tBodyGyroJerk_std_X

* tBodyGyroJerk_std_Y

* tBodyGyroJerk_std_Z

* tBodyAccMag_mean

* tBodyAccMag_std

* tGravityAccMag_mean

* tGravityAccMag_std

* tBodyAccJerkMag_mean

* tBodyAccJerkMag_std

* tBodyGyroMag_mean

* tBodyGyroMag_std

* tBodyGyroJerkMag_mean

* tBodyGyroJerkMag_std

* fBodyAcc_mean_X

* fBodyAcc_mean_Y

* fBodyAcc_mean_Z

* fBodyAcc_std_X

* fBodyAcc_std_Y

* fBodyAcc_std_Z

* fBodyAcc_meanFreq_X

* fBodyAcc_meanFreq_Y

* fBodyAcc_meanFreq_Z

* fBodyAccJerk_mean_X

* fBodyAccJerk_mean_Y

* fBodyAccJerk_mean_Z

* fBodyAccJerk_std_X

* fBodyAccJerk_std_Y

* fBodyAccJerk_std_Z

* fBodyAccJerk_meanFreq_X

* fBodyAccJerk_meanFreq_Y

* fBodyAccJerk_meanFreq_Z

* fBodyGyro_mean_X

* fBodyGyro_mean_Y

* fBodyGyro_mean_Z

* fBodyGyro_std_X

* fBodyGyro_std_Y

* fBodyGyro_std_Z

* fBodyGyro_meanFreq_X

* fBodyGyro_meanFreq_Y

* fBodyGyro_meanFreq_Z

* fBodyAccMag_mean

* fBodyAccMag_std

* fBodyAccMag_meanFreq

* fBodyBodyAccJerkMag_mean

* fBodyBodyAccJerkMag_std

* fBodyBodyAccJerkMag_meanFreq

* fBodyBodyGyroMag_mean

* fBodyBodyGyroMag_std

* fBodyBodyGyroMag_meanFreq

* fBodyBodyGyroJerkMag_mean

* fBodyBodyGyroJerkMag_std

* fBodyBodyGyroJerkMag_meanFreq
